inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - baza.gemspec

# https://github.com/AtomLinter/linter-rubocop/issues/2
Style/FileName:
  Enabled: false

# Metrics/CyclomaticComplexity:
#   Max: 10

# Metrics/LineLength:
#   Max: 160

# Metrics/MethodLength:
#   Max: 50

# Metrics/AbcSize:
#   Max: 25

# Metrics/ClassLength:
#   Max: 250

# .find_each is not the same as .each
Rails/FindEach:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLines:
  Enabled: false

# Will report offences for many places that are much more readable without using a guard clause
Style/GuardClause:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrivialAccessors:
  ExactNameMatch: true
  Enabled: true

# Disabled on purpose: https://github.com/bbatsov/rubocop/issues/1758
Style/ClosingParenthesisIndentation:
  Enabled: false
