language: ruby
rvm_old:
  #1.9.3-p551
  #jruby-1.7.13
rvm:
  - 2.1.2
before_script:
  - cp spec/info_mysql_shippable.rb spec/info_mysql.rb
  - cp spec/info_mysql2_shippable.rb spec/info_mysql2.rb
  - cp spec/info_pg_shippable.rb spec/info_pg.rb
  - cp spec/info_active_record_mysql_shippable.rb spec/info_active_record_mysql.rb
  - cp spec/info_active_record_mysql2_shippable.rb spec/info_active_record_mysql2.rb
  - cp spec/info_active_record_pg_shippable.rb spec/info_active_record_pg.rb
  - mysql -e 'CREATE DATABASE baza;'
  - psql -c 'DROP DATABASE IF EXISTS "baza";' -U postgres
  - psql -c 'CREATE DATABASE "baza";' -U postgres
script:
  - CODECLIMATE_REPO_TOKEN=98c06de7271764c9cd7bbde7cee4ddfa0d3e7db4bd9933f17779100276672e5f bundle exec rspec
  - bundle exec rake best_practice_project:run
notifications:
   email: false
