# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: baza 0.0.14 ruby lib

Gem::Specification.new do |s|
  s.name = "baza"
  s.version = "0.0.14"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Kasper Johansen"]
  s.date = "2014-10-15"
  s.description = "A database abstraction layer, model framework and database framework."
  s.email = "kj@gfish.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "baza.gemspec",
    "include/db.rb",
    "include/dbtime.rb",
    "include/driver.rb",
    "include/drivers/active_record/active_record.rb",
    "include/drivers/mysql/mysql.rb",
    "include/drivers/mysql/mysql_columns.rb",
    "include/drivers/mysql/mysql_indexes.rb",
    "include/drivers/mysql/mysql_sqlspecs.rb",
    "include/drivers/mysql/mysql_tables.rb",
    "include/drivers/sqlite3/libknjdb_java_sqlite3.rb",
    "include/drivers/sqlite3/libknjdb_sqlite3_ironruby.rb",
    "include/drivers/sqlite3/sqlite3.rb",
    "include/drivers/sqlite3/sqlite3_columns.rb",
    "include/drivers/sqlite3/sqlite3_indexes.rb",
    "include/drivers/sqlite3/sqlite3_sqlspecs.rb",
    "include/drivers/sqlite3/sqlite3_tables.rb",
    "include/dump.rb",
    "include/idquery.rb",
    "include/model.rb",
    "include/model_custom.rb",
    "include/model_handler.rb",
    "include/model_handler_sqlhelper.rb",
    "include/query_buffer.rb",
    "include/revision.rb",
    "include/row.rb",
    "include/sqlspecs.rb",
    "lib/baza.rb",
    "shippable.yml",
    "spec/include/drivers/active_record_spec.rb",
    "spec/include/drivers/mysql_spec.rb",
    "spec/include/drivers/sqlite3_spec.rb",
    "spec/info_active_record.rb",
    "spec/info_active_record_example.rb",
    "spec/info_active_record_shippable.rb",
    "spec/info_mysql_example.rb",
    "spec/info_mysql_shippable.rb",
    "spec/info_sqlite3.rb",
    "spec/model_handler_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/driver_collection.rb",
    "spec/support/driver_columns_collection.rb",
    "spec/support/driver_indexes_collection.rb",
    "spec/support/driver_tables_collection.rb"
  ]
  s.homepage = "http://github.com/kaspernj/baza"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.0"
  s.summary = "A database abstraction layer, model framework and database framework."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<datet>, [">= 0"])
      s.add_runtime_dependency(%q<wref>, [">= 0"])
      s.add_runtime_dependency(%q<knjrbfw>, [">= 0"])
      s.add_runtime_dependency(%q<array_enumerator>, [">= 0"])
      s.add_runtime_dependency(%q<string-cases>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<mysql2>, [">= 0"])
      s.add_development_dependency(%q<activerecord>, [">= 0"])
    else
      s.add_dependency(%q<datet>, [">= 0"])
      s.add_dependency(%q<wref>, [">= 0"])
      s.add_dependency(%q<knjrbfw>, [">= 0"])
      s.add_dependency(%q<array_enumerator>, [">= 0"])
      s.add_dependency(%q<string-cases>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<mysql2>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 0"])
    end
  else
    s.add_dependency(%q<datet>, [">= 0"])
    s.add_dependency(%q<wref>, [">= 0"])
    s.add_dependency(%q<knjrbfw>, [">= 0"])
    s.add_dependency(%q<array_enumerator>, [">= 0"])
    s.add_dependency(%q<string-cases>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<mysql2>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 0"])
  end
end

