# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: baza 0.0.35 ruby lib

Gem::Specification.new do |s|
  s.name = "baza".freeze
  s.version = "0.0.35"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Kasper Johansen".freeze]
  s.date = "2018-06-07"
  s.description = "A database abstraction layer, model framework and database framework.".freeze
  s.email = "kj@gfish.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    ".rubocop_todo.yml",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "baza.gemspec",
    "config/best_project_practice_rubocop.yml",
    "config/best_project_practice_rubocop_todo.yml",
    "lib/baza.rb",
    "lib/baza/base_sql_driver.rb",
    "lib/baza/cloner.rb",
    "lib/baza/column.rb",
    "lib/baza/commands.rb",
    "lib/baza/commands/importer.rb",
    "lib/baza/commands/select.rb",
    "lib/baza/database.rb",
    "lib/baza/database_model.rb",
    "lib/baza/database_model_functionality.rb",
    "lib/baza/database_model_name.rb",
    "lib/baza/db.rb",
    "lib/baza/dbtime.rb",
    "lib/baza/driver.rb",
    "lib/baza/driver/active_record.rb",
    "lib/baza/driver/active_record/columns.rb",
    "lib/baza/driver/active_record/commands.rb",
    "lib/baza/driver/active_record/databases.rb",
    "lib/baza/driver/active_record/indexes.rb",
    "lib/baza/driver/active_record/result.rb",
    "lib/baza/driver/active_record/tables.rb",
    "lib/baza/driver/active_record/users.rb",
    "lib/baza/driver/mysql.rb",
    "lib/baza/driver/mysql/column.rb",
    "lib/baza/driver/mysql/columns.rb",
    "lib/baza/driver/mysql/commands.rb",
    "lib/baza/driver/mysql/database.rb",
    "lib/baza/driver/mysql/databases.rb",
    "lib/baza/driver/mysql/foreign_key.rb",
    "lib/baza/driver/mysql/index.rb",
    "lib/baza/driver/mysql/indexes.rb",
    "lib/baza/driver/mysql/result.rb",
    "lib/baza/driver/mysql/sql.rb",
    "lib/baza/driver/mysql/sql/column.rb",
    "lib/baza/driver/mysql/sql/create_indexes.rb",
    "lib/baza/driver/mysql/sql/create_table.rb",
    "lib/baza/driver/mysql/sqlspecs.rb",
    "lib/baza/driver/mysql/table.rb",
    "lib/baza/driver/mysql/tables.rb",
    "lib/baza/driver/mysql/unbuffered_result.rb",
    "lib/baza/driver/mysql/user.rb",
    "lib/baza/driver/mysql/users.rb",
    "lib/baza/driver/mysql2.rb",
    "lib/baza/driver/mysql2/column.rb",
    "lib/baza/driver/mysql2/columns.rb",
    "lib/baza/driver/mysql2/commands.rb",
    "lib/baza/driver/mysql2/database.rb",
    "lib/baza/driver/mysql2/databases.rb",
    "lib/baza/driver/mysql2/index.rb",
    "lib/baza/driver/mysql2/indexes.rb",
    "lib/baza/driver/mysql2/result.rb",
    "lib/baza/driver/mysql2/table.rb",
    "lib/baza/driver/mysql2/tables.rb",
    "lib/baza/driver/mysql2/user.rb",
    "lib/baza/driver/mysql2/users.rb",
    "lib/baza/driver/mysql_java.rb",
    "lib/baza/driver/mysql_java/column.rb",
    "lib/baza/driver/mysql_java/columns.rb",
    "lib/baza/driver/mysql_java/commands.rb",
    "lib/baza/driver/mysql_java/database.rb",
    "lib/baza/driver/mysql_java/databases.rb",
    "lib/baza/driver/mysql_java/index.rb",
    "lib/baza/driver/mysql_java/indexes.rb",
    "lib/baza/driver/mysql_java/table.rb",
    "lib/baza/driver/mysql_java/tables.rb",
    "lib/baza/driver/mysql_java/user.rb",
    "lib/baza/driver/mysql_java/users.rb",
    "lib/baza/driver/pg.rb",
    "lib/baza/driver/pg/column.rb",
    "lib/baza/driver/pg/columns.rb",
    "lib/baza/driver/pg/commands.rb",
    "lib/baza/driver/pg/create_index_sql_creator.rb",
    "lib/baza/driver/pg/database.rb",
    "lib/baza/driver/pg/databases.rb",
    "lib/baza/driver/pg/foreign_key.rb",
    "lib/baza/driver/pg/index.rb",
    "lib/baza/driver/pg/indexes.rb",
    "lib/baza/driver/pg/result.rb",
    "lib/baza/driver/pg/table.rb",
    "lib/baza/driver/pg/tables.rb",
    "lib/baza/driver/sqlite3.rb",
    "lib/baza/driver/sqlite3/column.rb",
    "lib/baza/driver/sqlite3/columns.rb",
    "lib/baza/driver/sqlite3/commands.rb",
    "lib/baza/driver/sqlite3/database.rb",
    "lib/baza/driver/sqlite3/databases.rb",
    "lib/baza/driver/sqlite3/index.rb",
    "lib/baza/driver/sqlite3/indexes.rb",
    "lib/baza/driver/sqlite3/result.rb",
    "lib/baza/driver/sqlite3/sqlspecs.rb",
    "lib/baza/driver/sqlite3/table.rb",
    "lib/baza/driver/sqlite3/tables.rb",
    "lib/baza/driver/sqlite3/unbuffered_result.rb",
    "lib/baza/driver/sqlite3_java.rb",
    "lib/baza/driver/sqlite3_java/column.rb",
    "lib/baza/driver/sqlite3_java/columns.rb",
    "lib/baza/driver/sqlite3_java/commands.rb",
    "lib/baza/driver/sqlite3_java/database.rb",
    "lib/baza/driver/sqlite3_java/index.rb",
    "lib/baza/driver/sqlite3_java/indexes.rb",
    "lib/baza/driver/sqlite3_java/table.rb",
    "lib/baza/driver/sqlite3_java/tables.rb",
    "lib/baza/driver/sqlite3_java/unbuffered_result.rb",
    "lib/baza/driver/sqlite3_rhodes.rb",
    "lib/baza/driver/tiny.rb",
    "lib/baza/driver/tiny/commands.rb",
    "lib/baza/driver/tiny/result.rb",
    "lib/baza/dump.rb",
    "lib/baza/errors.rb",
    "lib/baza/foreign_key.rb",
    "lib/baza/idquery.rb",
    "lib/baza/index.rb",
    "lib/baza/jdbc_driver.rb",
    "lib/baza/jdbc_result.rb",
    "lib/baza/mysql_base_driver.rb",
    "lib/baza/query_buffer.rb",
    "lib/baza/result_base.rb",
    "lib/baza/row.rb",
    "lib/baza/sql_queries.rb",
    "lib/baza/sql_queries/generic_insert.rb",
    "lib/baza/sql_queries/generic_update.rb",
    "lib/baza/sql_queries/mysql_upsert.rb",
    "lib/baza/sql_queries/mysql_upsert_duplicate_key.rb",
    "lib/baza/sql_queries/non_atomic_upsert.rb",
    "lib/baza/sql_queries/postgres_upsert_duplicate_key.rb",
    "lib/baza/sql_queries/select.rb",
    "lib/baza/sql_queries/sqlite_upsert_duplicate_key.rb",
    "lib/baza/sqlspecs.rb",
    "lib/baza/table.rb",
    "lib/baza/tables.rb",
    "peak_flow.yml",
    "spec/active_record/models/user.rb",
    "spec/baza/cloner_spec.rb",
    "spec/baza/sql_queries/generic_insert_spec.rb",
    "spec/baza/sql_queries/select_spec.rb",
    "spec/drivers/active_record_mysql2_spec.rb",
    "spec/drivers/active_record_mysql_spec.rb",
    "spec/drivers/active_record_pg_spec.rb",
    "spec/drivers/active_record_sqlite3_spec.rb",
    "spec/drivers/mysql2_spec.rb",
    "spec/drivers/mysql_spec.rb",
    "spec/drivers/pg/columns_spec.rb",
    "spec/drivers/pg_spec.rb",
    "spec/drivers/sqlite3_spec.rb",
    "spec/info_active_record_example.rb",
    "spec/info_active_record_mysql2_example.rb",
    "spec/info_active_record_mysql2_peak_flow.rb",
    "spec/info_active_record_mysql_example.rb",
    "spec/info_active_record_mysql_peak_flow.rb",
    "spec/info_active_record_pg_example.rb",
    "spec/info_active_record_pg_peak_flow.rb",
    "spec/info_active_record_sqlite3.rb",
    "spec/info_mysql2_example.rb",
    "spec/info_mysql2_peak_flow.rb",
    "spec/info_mysql_example.rb",
    "spec/info_mysql_peak_flow.rb",
    "spec/info_pg_example.rb",
    "spec/info_pg_peak_flow.rb",
    "spec/info_sqlite3.rb",
    "spec/spec_helper.rb",
    "spec/support/driver_active_record_collection.rb",
    "spec/support/driver_collection.rb",
    "spec/support/driver_columns_collection.rb",
    "spec/support/driver_databases_collection.rb",
    "spec/support/driver_foreign_keys_collection.rb",
    "spec/support/driver_importer_collection.rb",
    "spec/support/driver_indexes_collection.rb",
    "spec/support/driver_tables_collection.rb",
    "spec/support/driver_users_collection.rb"
  ]
  s.homepage = "http://github.com/kaspernj/baza".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.7".freeze
  s.summary = "A database abstraction layer, model framework and database framework.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<array_enumerator>.freeze, ["~> 0.0.10"])
      s.add_runtime_dependency(%q<auto_autoloader>.freeze, ["~> 0.0.5"])
      s.add_runtime_dependency(%q<datet>.freeze, ["~> 0.0.25"])
      s.add_runtime_dependency(%q<event_handler>.freeze, ["~> 0.0.0"])
      s.add_runtime_dependency(%q<simple_delegate>.freeze, ["~> 0.0.2"])
      s.add_runtime_dependency(%q<string-cases>.freeze, ["~> 0.0.4"])
      s.add_runtime_dependency(%q<wref>.freeze, ["~> 0.0.8"])
      s.add_development_dependency(%q<activerecord>.freeze, ["= 4.2.5"])
      s.add_development_dependency(%q<activerecord-jdbc-adapter>.freeze, [">= 0"])
      s.add_development_dependency(%q<best_practice_project>.freeze, ["= 0.0.9"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_development_dependency(%q<jdbc-mysql>.freeze, [">= 0"])
      s.add_development_dependency(%q<jdbc-sqlite3>.freeze, [">= 0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["= 2.3.9"])
      s.add_development_dependency(%q<mysql2>.freeze, ["= 0.4.10"])
      s.add_development_dependency(%q<pg>.freeze, ["= 0.21.0"])
      s.add_development_dependency(%q<pry>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, [">= 0"])
      s.add_development_dependency(%q<rspec>.freeze, ["= 3.4.0"])
      s.add_development_dependency(%q<rubocop>.freeze, ["= 0.39.0"])
      s.add_development_dependency(%q<sqlite3>.freeze, [">= 0"])
    else
      s.add_dependency(%q<array_enumerator>.freeze, ["~> 0.0.10"])
      s.add_dependency(%q<auto_autoloader>.freeze, ["~> 0.0.5"])
      s.add_dependency(%q<datet>.freeze, ["~> 0.0.25"])
      s.add_dependency(%q<event_handler>.freeze, ["~> 0.0.0"])
      s.add_dependency(%q<simple_delegate>.freeze, ["~> 0.0.2"])
      s.add_dependency(%q<string-cases>.freeze, ["~> 0.0.4"])
      s.add_dependency(%q<wref>.freeze, ["~> 0.0.8"])
      s.add_dependency(%q<activerecord>.freeze, ["= 4.2.5"])
      s.add_dependency(%q<activerecord-jdbc-adapter>.freeze, [">= 0"])
      s.add_dependency(%q<best_practice_project>.freeze, ["= 0.0.9"])
      s.add_dependency(%q<bundler>.freeze, [">= 0"])
      s.add_dependency(%q<jdbc-mysql>.freeze, [">= 0"])
      s.add_dependency(%q<jdbc-sqlite3>.freeze, [">= 0"])
      s.add_dependency(%q<jeweler>.freeze, ["= 2.3.9"])
      s.add_dependency(%q<mysql2>.freeze, ["= 0.4.10"])
      s.add_dependency(%q<pg>.freeze, ["= 0.21.0"])
      s.add_dependency(%q<pry>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, [">= 0"])
      s.add_dependency(%q<rspec>.freeze, ["= 3.4.0"])
      s.add_dependency(%q<rubocop>.freeze, ["= 0.39.0"])
      s.add_dependency(%q<sqlite3>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<array_enumerator>.freeze, ["~> 0.0.10"])
    s.add_dependency(%q<auto_autoloader>.freeze, ["~> 0.0.5"])
    s.add_dependency(%q<datet>.freeze, ["~> 0.0.25"])
    s.add_dependency(%q<event_handler>.freeze, ["~> 0.0.0"])
    s.add_dependency(%q<simple_delegate>.freeze, ["~> 0.0.2"])
    s.add_dependency(%q<string-cases>.freeze, ["~> 0.0.4"])
    s.add_dependency(%q<wref>.freeze, ["~> 0.0.8"])
    s.add_dependency(%q<activerecord>.freeze, ["= 4.2.5"])
    s.add_dependency(%q<activerecord-jdbc-adapter>.freeze, [">= 0"])
    s.add_dependency(%q<best_practice_project>.freeze, ["= 0.0.9"])
    s.add_dependency(%q<bundler>.freeze, [">= 0"])
    s.add_dependency(%q<jdbc-mysql>.freeze, [">= 0"])
    s.add_dependency(%q<jdbc-sqlite3>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, ["= 2.3.9"])
    s.add_dependency(%q<mysql2>.freeze, ["= 0.4.10"])
    s.add_dependency(%q<pg>.freeze, ["= 0.21.0"])
    s.add_dependency(%q<pry>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, ["= 3.4.0"])
    s.add_dependency(%q<rubocop>.freeze, ["= 0.39.0"])
    s.add_dependency(%q<sqlite3>.freeze, [">= 0"])
  end
end

