before_install:
  - sudo apt-get install -y libmysqlclient-dev
before_script:
  - cp spec/info_mysql_peak_flow.rb spec/info_mysql.rb
  - cp spec/info_mysql2_peak_flow.rb spec/info_mysql2.rb
  - cp spec/info_pg_peak_flow.rb spec/info_pg.rb
  - cp spec/info_active_record_mysql_peak_flow.rb spec/info_active_record_mysql.rb
  - cp spec/info_active_record_mysql2_peak_flow.rb spec/info_active_record_mysql2.rb
  - cp spec/info_active_record_pg_peak_flow.rb spec/info_active_record_pg.rb
services:
  postgres:
    environment:
      POSTGRES_USER: "build"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "baza"
    expose:
      - 5432
    image: postgres:11.4
  mysql:
    environment:
      - MYSQL_USER=build
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=baza
    image: mysql:5.7.29
    expose:
      - 3306
script:
  - bundle exec rspec --tag ~@mysql
  - bundle exec rake best_practice_project:run
